export {default as TvSeries} from "./TvSeries"
export {default as Movies} from "./Movies"
export {default as Login} from "./Login"
export {default as Home} from "./Home"
export {default as Bookmarks} from "./Bookmarks"
export {default as SingUp} from "./SignUp"
