export {default as Logo} from "./Logo"
export {default as Home} from "./Home"
export {default as Movie} from "./Movie"
export {default as TvSeries} from "./TvSeries"
export {default as Bookmarks} from "./Bookmarks"